version: "3.4"

services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    working_dir: /app
    environment:
      NODE_ENV: development
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
      JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}
    command: node app.js
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "./mongo_data:/data/db"
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
