FROM ubuntu:18.04
# Create app directory
RUN mkdir -p /app

WORKDIR /app


RUN \
        apt-get update && \
        apt-get clean && \
        apt-get install -y curl build-essential libfontconfig ffmpeg


RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1


# Install node
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install nodejs -y

# For autorestart of server
RUN npm install -g nodemon@2.0.7

# For Testing
RUN npm install -g jest@24.8.0

# Install app dependencies
COPY package.json /app
RUN npm install

# Bundle app source
COPY . /app
